"""El orden correcto de la lista es:
    1. Palabra Quechua
    2. Definición
"""

dicc_qu_esp = {
    "a": "[a]. Apócope de ari. Pues.",
    "achachay": "achachaw! interj. ¡Qué frío!",
    "achakana": "s. Una de las variedades de cacto de raíz comestible.",
    "achaki": "tr. Culpar a uno de algo, con mentira; calumniar",
    "achalachiy": "achhalay. tr. Decorar. Adornar, Hermosear. // Soltar, desasir lo que estaba sujeto. "
                  "Wataray, watannay, phaskay. // intr. Irse, marcharse. Ripuy. // prnl. Escaparse. "
                  "Ayqipuy, llusp'ipuy. // Dislocarse una coyuntura. Ch'utay, muq'akuy",
    "chaki": "s. Pie.",
    "icha ari": "Ichasapas. Ojalá! interj. de deseo vehemente.",
    "khacha": "adj. Aplícase a la mugre encostrada y áspera. //U Dicese de la piel callosa y pringosa",
    "": "",
}

dicc_esp_qu = {

    "a": "prep. Indica la dirección o el térmikno de alguna persona o cosa. Sufijo -man. //"
         " Denota el objeto o complemento de la acción del verbo. Sufijo -ta: Yo a tí te digo. Ñuqa qamta niyki.",
    "ábaco": "andino. s. Yupana.",
    "abajo": "adv. Hacia lugar o parte inferior. Uray.",
    "abanderado": "adj. s. El que lleva la bandera en procesiones o festejos públicos.",
    "abandonado": "p. p. Desamparado, dejado. Saqisqa, jaqisqa.",
    "abandonar": "tr. Desamparar. Saqiy, jaqiy, saqirpariy.",
    "abandono": "s. Desamparo, dejadez. Saqisqa.",
    "abanicar": "tr. prnl. Hacer aire con el abanico. Wayrachiy, phukuy, laphay.",
    "abanico": "s. Instrumento para hacer o hacerse aire. Wayrachina, laphachu.",
    "abaratar": "tr. Disminuir o bajar el precio de una cosa. Chaninnay. Pisiyachiy, uraqay, uraykuchiy.",
    "abarca": "s. Juk'uta, usuta.",
    "abarcar": "tr. Ceñir o llevar con los brazos. Marq'ay. // Ceñir, rodear. Uqllay.",
    "abarrote": "s. pl. Artículos de comercio comestibles. Mikhuna qhatu.",
    "abasto": "s. Provisión de cosas y víveres. Qhatu.",
    "abatido": "adj. Desmirriado, flaco, agotado. Yumpaqa. // Postrado, desalentado. Willpusqa.",
    "abatir": "tr. Derribar, tumbar. Hacer que baje una cosa que antes tenía la posición vertical. Maray.",
    "abseso": "s. Tumor, divieso. Ch'upu.",
    "abdicar": "tr. Ceder o renunciar una dignidad, rendirse. Wasqiy.",
    "abdomen": "s. Wiksa.",
    "abecedario": "s. Alfabeto u orden alfabético. Sanampana, sanampa qillqa, sanampakuna.",
    "abeja": "s. Insecto himenóptero. Wara. // Abeja nativa. T'uktu.",
    "abejar": "s. Colmenar, lugar donde están las colmenas. Wanquyru t'iqi. wanquyru thapa.",
    "abejorro": "s. Insecto himenóptero, velludo, que zumba mucho al volar. Wayrunq'u, wanquyru, wanquyra.",
    "aberración": "s. Extravío, desorientación. Pawi. //Error, equivocación, confusión. Pantay.",
    "abertura": "s. Boca, hendidura. Kicha. // Agujero. Julk'u",
    "abierto": "adj. Kichasqa, kicha.",
    "abigarrado": "adj. De varios colores mal combinados. Saqsa.",
    "abigeato": "s. Hurto de ganado. Uywa suwaku.",
    "abigotado": "adj. Bigotudo. Sunkhasapa.",
    "abismo": "s. Profundidad grande y peligrosa. Wañuy ukhu, millay ukhu (sinón. infierno).",
    "ablandar": "tr. prnl. Poner blanda una cosa. Mupuchay. //Suavizar. Lamp'uy. // "
                "Moler hasta convertir en polvo. Ñut'uy.",
    "ablandarse": "prnl. Ponerse blando. Tikmuyay, llamp'uyay.",
    "abobar": "tr. Hacer bobo a alguien. Luqt'uyachiy, luqluwachiy.",
    "abocar": "tr. Asir con la boca. Achuy, achulliy.",
    "abochornado": "adj. fig. Sonrojado. Pinq'achikusqa.",
    "abochornar": "tr. Sonrojar. P'inqachiy, pukayachiy. // Causar bochorno el excesivo calor. K'ajachiy, sansachiy. //"
                  " prnl. Sonrojarse. P'inqakuy.",
    "abofetear": "tr. Dar de bofetadas. Ch'aqllay, t'aqllay, jinch'ay, k'akllanchay, qallanchay, laqhay.",
    "abogado": "s. Amachaq, amachaqi. // Intercesor. Rimapuqi, rimaysiq.",
    "abogar": "intr. Defender en juicio. Amachay. // Interceder. Rimapuy, rimaysiy.",
    "abolir": "tr. Derogar un  precepto o costumbre. Suprimir. Q'ullway, q'ullwachay.",
    "abollado": "p.p. Q'apñusqa, t'añusqa, ñat'usqa. (sinón. aplastado)",
    "abollar": "tr. Producir hundimientos en una superficie con uno o varios golpes. Q'apñuy, ñat'uy, t'añuy.",
    "abominar": "tr. Aborrecer. Chiqniy.",
    "abonar": "tr. Echar en tierra laborable materias que aumenten su fertilidad. Wanuchay. // "
              "Beneficiar la tierra para el cultivo. Kullachay, ruq'ay.",
    "abono": "s. Sustancia con que se fertiliza la tierra. Wanu, kullcha, ruq'a.",
    "aborigen": "adj. Yuriqi. // El primitivo morador de una nación Ñawpa runa, wari runa.",
    "aborrecer": "tr. Tener una aversión a una persona o cosa. Chiqniy.",
    "aborrecible": "adj. Abominable, que se puede odiar. Chiqnina.",
    "aborrecido": "adj. Chiqnisqa.",
    "aborrecimiento": "s. Chiqniy, milla.",
    "abortar": "intr. Parir antes de tiempo. Sulluy.",
    "aborto": "s. Lo abortado. Sullu.",
    "abotonar": "tr. Abrochar, cerrar con botones una prenda de vestir. Ch'itay.",
    "abrasador": "adj. Rupha, k'ajaq, ruphaq, k'anaq, k'ananaq.",
    "abrasar": "tr. Reducir a brasa. Sansachiy, k'ajachiy. // Calentar demasiado. K'anachiy, ruphay.",
    "abrazar": "tr. Ceñir con los brazos. Uqllay.",
    "abrazarse": "re. Uqllanakuy, mak'allinakuy.",
    "abrazo": "s. Mak'alli, uqllay, uqllu.",
    "abrevadero": "s. Paraje del río, arrollo o manantial para dar de beber al ganado. Ukyana pukyu, ukyana p'unqu.",
    "abrevar": "tr. Dar de beber al ganado. Yakuchiy, ukyachiy.",
    "abreviar": "tr. Hacer breve, acortar, reducir a menos tiempo o espacio. Jayrichay.",
    "abridor": "adj.s. Instrumento que abre. Kichariq, kicharina.",
    "abrigar": "tr. Defender, resguardar del frío. Qhatay.",
    "abrigo": "s. Cobija, defensa contra el frío. Qhata.",
    "abril": "s. Ariwaki killa, (ver mes).",
    "abrillantar": "tr. dar brillantez. Lliphichiy.",
    "abrir": "tr. Kichay, kichariy, ichilliy. // prnl. Abrirse la flor. Phanchiy, phanchay.",
    "abrumar": "tr. Agobiar. Machitay, mach'itay.",
    "absceso": "tr. Remitir a un penitente sus pecados o levantarle las censuras en que hubiere incurrido, perdonar. "
               "Phaskay.",
    "absolver": "tr. Remitir a un penitente sus pecados o levantarle las censuras en que hubiere incurrido, perdonar. "
                "Phaskay.",
    "absorber": "tr. Chupar, atraer hacia dentro de sí algunas cosas aunque no sean líquidas. Ch'unqay, suq'uy.",
    "abstención": "s. Sasi. // Ayuno. Sasi.",
    "abstenerse": "prnl. Privarse de alguna cosa. Sasikuy.",
    "abstracción": "s. Meditación. T'uku.",
    "abuchear": "tr. Reprobar públicamente y de manera ruidosa. Japapiyay.",
    "abuela": "s.f. Mujer anciana. Jatun mama. // fig. Payala.",
    "abuelo": "Hombre anciano. Jatun tata, jatun yaya, apucha, apuski.",
    "abundante": "adj. Abombado, avejigado. P'uli.",
    "abultado": "adj. Achkha, chay chhika.",
    "aburridor": "Molestoso. Majiq",
    "aburrimiento": "s. Fastidio, tedio, cansancio. Maji. // Hastío, empalagamiento. Maji, ami.",
    "aburrir": "tr. Hastiar, cansar, molestar, fastidiar. Majichiy, uychuchiy.",
    "aburrirse": "prnl. Majiy.",
    "abusar": "tr. Usar mal, impropia, indebida y excesivamente de algo o alguien. Atiy millp'uy.",
    "abusivo": "adj. Atiy millp'u.",
    "acá": "adv. En este lugar. Kaypi. // A este lugar. Kayman.",
    "acabar": "tr. Dar fin a una cosa. Tukuy, p'unchay, tukuychay.",
    "acabarse": "prln. Jiwiqay, tukukuy, p'uchukakuy.",
    "acallar": "tr. Hacer callar. Ch'inyachiy, chhustachiy. // Acallar a un niño. Chhukuy.",
    "acampar": "intr. Detenerse y permanecer en el campo. Tampuchay, tampuy.",
    "acaparador": "adj. El que acapara. Mak'alli, mak'alliq.",
    "acaparar": "tr. Apropiarse de una cosa en perjuicio de los demás. Mak'alliy.",
    "acariciar": "tr. Tratar a alguien con ternura. Waylluy. // Acariciar una paloma a otra. Chinuy.",
    "acarrear": "tr. Transportar. Astay.",
    "acatar": "tr. Tributar homenaje de sumisión. Yupaychay. // Obedecer. Yulliy, qhawqatay, qhawaqatay.",
    "acaudalado": "adj. Illayuq, usapu, allinniyuq. Qhapaq",
    "acceder": "v. intr. Tener acceso a una situación, condición o grados superiores. Juniy, chay ñiy. || "
               "Aceptar, prometer. Simin ñiy",
    "accesible": "adj. De fácil acceso. Chayaykuna, asuykuna",
    "accidentado": "adj. Terreno escabroso. Chhapu chhapu",
    "accidente": "s. Suceso o acción de que involuntariamente resulta daño para personas o cosas. Aquyra.",
    "acechar": "v. tr. Observar cautelosamente con algun propósito. Watiqay, qhawmiy, qaymiway, chapatiyay, chapay.",
    "acecinar": "v. tr. Salar las carnes y secarlas al sol, para que se conserven. Ch’arkiy",
    "aceitar": "v. tr. Untar, bañar con aceite. Lluklluchay, jawilluy.",
    "aceite": "s. Llukllu. Jawillu.",
    "aceitera": ". s. frasco u otro cuerpo donde se guarda el aceite. Llukllu churana.",
    "acelerar": "v. tr. Aumentar la velocidad. Utqhay, sinchichiy, p’ikwachiy.",
    "acento": "s. La mayor intensidad con que se pronuncia una sílaba de una palabra. Ankaylli uqharina",
    "aceptar": "v. tr. Recibir uno voluntariamente lo que se le da o encarga. Ari ñiy",
    "acequia": "s. Zanja por donde se conduce el agua para regar, etc. Larq’a, larq’a. || Perú. Yarqha.",
    "acercamiento": "s. Aproximación. Asuy.",
    "acercar": "v. tr. Poner cerca o a menor distancia. Qayllachiy, asuchiy, achhuchiy, k’askachiy, sispachiy, "
               "chimpachiy",
    "acercarse": "v. prnl. Qayllay, qayllakuy, sispay, chimpay.",
    "acertijo": "s. Adivinanza propuesta como pasatiempo. Watuchi. Achinay.",
    "achacar": "v. tr. Atribuir, imputar. Tumpay",
    "achacoso": "adj. Que padece achaque habitual. Qarwa runa, umphu, wañuq wañuq. Chullchu, chullchuq, tunuku.",
    "achatar": "v. tr. Poner chata alguna cosa. T’añuy, q’apñuy.",
    "achicharrar": " v. tr. Freir, asar un manjar hasta que tome un sabor a quemado. Kankay",
    "achira": "s. Achira",
    "acicalar": ". v. tr. Adornar a una persona. Aknupulliy",
    "acicalarse": "v. prnl. Ch’antakuy.",
    "aclarar": "v. tr. Quitar lo que ofusca la claridad de alguna cosa. Sut’ichay, sut’inchay. || "
               "Purificar un líquido. Ch’uwachay, ch’uwayachiy.",
    "acobardar": "v. tr. Amedrentar. Llakllachiy, q’iwachiy.",
    "acobardarse": "v. prnl. Llakllay, q’iwakuy, jallk’akuy.",
    "acoger": "v. tr. Admitir uno en su casa a otra persona. Qurpachay.",
    "acolchar": "v. tr. Poner algodón, lana, estopa entre dos telas y después bastearlas. T’iqiy, t’iqinchay, "
                "t’akuchay, phatunchay.",
    "acongojar": "v. tr. Angustiar, afligir.",
    "acopiar": "v. tr. Juntar, reunir en cantidad alguna cosa. Tantay, jujuy, qhuchuy, qutuy",
    "acopio": "s. Reunión, gran cantidad de algo. Tanta, tantalliku, juñulliku",
    "acordar": "v. tr. Determinar o resolver de común acuerdo, o por mayoría. Uyñinakuy",
    "acordarse": "v. prnl. Recordar. Yuyariy, yuyarikuy. || Yalpay.",
    "acorralar": "v. tr. Encerrar el ganado en el corral. Jip’iy, jip’ichay.",
    "acortar": "v. tr. e intr. Disminuir la longitud, duración, etc. de alguna cosa. Pisichay, taksachay, "
               "juch’uyyachiy, juch’uychay.",
    "acostar": "v. tr. Echar a alguno para que duerma o descanse. Puñuykuchiy.",
    "acostarse": "v. prnl. Puñuykuy. || Recostarse, echarse. Siriy, siriykukuy",
    "acostumbrado": ". p.p. Yachasqa, yachallisqa",
    "acostumbrar": "v. tr. Hacer adquirir costumbre. Yachaykuchiy, yachachiy, yachallichiy",
    "acostumbrarse": "v. prnl. Adaptarse. Yachakuy.",
    "acrecentamiento": "s. Aumento. Achkachay",
    "acrecentar": "v. tr. Aumentar. Yapay, achkhachay, achkhayachiy, achkayachiy",
    "acreedor": "adj. y s. Persona a la que se debe dinero. Manuq.",
    "acróbata": "com. Persona que hace ejercicios de agilidad y de equilibrio con gran habilidad. Qiwillinku",
    "activo": "adj. Que obra o tiene virtud de obrar. P’itu, p’itulli, k’uchi, wallpaywana.",
    "actual": "adj. Prsente. Kunan, kunanpa.",
    "actualmente": "adv. En el tiempo presente. Kunan pacha",
    "acuchillar": "v. tr. Dar cuchilladas, cortar. Khariy. || T’uqsiy.",
    "acuclillarse": "v. prnl. Ponerse en cuclillas. Chukuy, chukukuy, runkhukuy; usthuy.",
    "acueducto": "s. Conducto artificial por donde va el agua a un lugar determinado. Pincha, rarq’a, larq’a. Witkhu",
    "acuerdo": "s. Resolución tomada por una o varias personas. Uyñi, uyñiku.",
    "acumular": "v. tr. Juntar. Tantay, qutuy, phinay, qhuchuy, suntuy.",
    "acunar": " v. tr. Cunear, mecer la cuna. Chhukuy.",
    "acuñar": "v. tr. Meter cuñas, apoyar. Q’imiy, qimiy, chillpay. Tusay",
    "acusar": ". v. tr. Denunciar. Ch’atay. || Imputar a uno algún delito. Tumpay",
    "adelantar": "v. tr. Anticipar. Ñawpachiy.",
    "adelantarse": "v. prnl. Ñawpay, ñawpatay",
    "adelante": "adv. Denota tiempo futuro. Qhipa, qhipa pacha. || Anticipación. Ñawpaq",
    "adelgazar": "v. tr. Poner delgado. Ñañuchiy, ñañuyachiy, ñañuchay, ñañuy. || v. prnl. Ñañuyay.",
    "adentro": "adv. Lugar interior. Ukhu. || al lugar interior. Ukhuman. || En el interior. Ukhupi.",
    "aderezar": ". v. tr. Aliñar. Allichay. || Guisar, condimentar o sazonar los alimentos. Wakichiy",
    "adherir": "v. tr. Pegar una cosa a otra. K’askachiy, rat’ay, mach’ay. || v. prnl. K’askakuy.",
    "adhesivo": "adj. Capaz de adherirse. Mach’a. || Sustancia que sirve para pegar dos cuerpos. Mach’a. K’askachina.",
    "adicionar": "v. tr. Hacer o poner adiciones. Yapay",
    "adicto": "adj. y s. Simpatizante, partidario, adepto. Sayaqi.",
    "adiestrador": "adj. Que adiestra. Yachachiq",
    "adiestrar": "v. tr. Enseñar, instruir. Yachachiy. Ñamkay.",
    "adiós": "s. Partida, despedida. Aywa, aywariku",
    "adivinanza": "s. Acertijo. Watuy.",
    "adivinar": "v. tr. Predecir el futuro o descubrir las cosas ocultas, por medio de agüeros o sortilegios o por "
                "conjeturas. Watuy, achinay",
    "adivino": "s. Persona que adivina. Watuq. Wamuni, umu. || fig. Hechicero, brujo. Layqa",
    "administrar": "v. tr. Gobernar, regir. Kamachiy.",
    "admirable": "adj. Digno de admiración. T’ukuchiq, t’ukuna, llaksana.",
    "admiración": "s. Cosa admirable. Añay. Llaksaku, t’ukuku",
    "admirar": "v. tr. y prnl. Ver, contemplar con sorpresa, asombrarse. Añay, utirayay. T’ukuy",
    "admisible": "adj. Que se admite. Chaskina",
    "admitir": "v. tr. Recibir, dar entrada. Ari ñiy, chaskiy, jap’ikuy. || Recibir en la memoria. Jap’iqay.",
    "adobar": ". v. tr. Poner en adobo. Jillp’uy, jupt’ay, wakichiy",
    "adobe": "s. Masa de barro moldeada en forma de ladrillo y secada al sol. Tika.",
    "adobera": "s. Molde para hacer adobes. Tikana",
    "adolescente": "adj. y s. Que está en la adolescencia. Maqt’a, warma, q’aqu.",
    "adolorido": "adj. Nanasqa",
    "adonde": "adv. A qué parte. Mayman, mayñiqman",
    "adoptar": "v. tr. Prohijar. Churichakuy, jawaychay.",
    "adoptivo": "adj. Que ha sido adoptado. m. jaway churo. f. Jaway ususi. m. y f. Jaway wawa",
    "adoquín": ". s. Piedra labrada para empedrados, etc. Khallki, qalla.",
    "adoquinar": ". v. tr. Labrar o hacer adoquines. Khallkiy.",
    "adorable": "adj. Much’ana, yupaychana, wak’anchana",
    "adoración": "s. Acción de adorar. Much’ay.",
    "adorar": "v. tr. Reverenciar o amar a un ser. Much’ay, yupaychay, wak’anchay",
    "adormecer": "v. tr. Hacer entorpecer o causar sueño. Tunuyachiy, susunkachiy.",
    "adormecerse": " v. prnl. Entorpecerse o empezar a dormirse. Tunuyay, k’aywiy, susunkay.",
    "adormecido": "adj. Tunu.",
    "adormecimiento": "s. Uti, tunuya.",
    "adormilarse": "v. prnl. Dormirse a medias. K’aywiy, pungí ch’utay (sinón.: Adormitarse).",
    "adornar": ". v. tr. Engalanar con adornos. K’achanchay, kaskichay, achhalay, sañay. || Adornar con banderines "
               "y flores. T’ikachay, t’ikanchay.",
    "adorno": "s. Warawa, kaski, achhalana, sañana",
    "adosar": "v. tr. Poner una cosa contigua o arrimada a otra. Q’imiy.",
    "adquirir": "v. tr. Conseguir u obtener una cosa. Jaypay, taripay.",
    "adrede": "adv. De intento. Wak tanta, wak tantamanta.",
    "adulador": "adj. y s. Lisonjero, que adula. Llunk’u, misk’iq simi, qhanaymachi (sinón.: Adulón).",
    "adular": "v. tr. Halagar. Llunk’uy, qhanaymay",
    "adúltera": "adj. y s. Wachuq.",
    "adulterar": "v. intr. Cometer adulterio. Wach’uy, ayuy, jawanchay.",
    "adúltero": "adj. y s. Añasu.",
    "adulto": "adj. Llegado a su mayor crecimiernto. Puriq",
    "adulzar": "v. tr. Endulzar. Llawichay. Misk’ichay.",
    "adunarse": ". v. prnl. Unirse, juntarse varias personas. Uqllachakuy.",
    "adversario": "s. Rival. Awqa, jayu.",
    "adversidad": "s. Desventura. Aquyraki, ati.",
    "advertir": ". v. tr. Reparar, fijar la atención en una cosa. Musyay, rikuy, ch’ukiy.",
    "afable": "adj. Misk’i simi.",
    "afanarse": "v. prnl. Bregar, trabajar con ahínco. Allpariy, p’ituy",
    "afear": "v. tr. Hacer o poner fea a una persona o cosa. Millaychay",
    "afeitarse": "v. prnl. Mumikuy, paryakuy.",
    "afeminado": "adj. y s. m. Parecido a una mujer. Maqlla, waqati, q’iwsa.",
    "afilar": ". v. tr. Sacar filo o punta. K’awchiy, ñawch’iy, t’upay, thupray, saqay.",
    "afirmar": "v. tr. Asegurar o dar por cierta alguna cosa. Chiqan ñiy, chi ñiy, taksachiy.",
    "afirmarse": "v. prnl. Taksay, takyay.",
    "aflicción": "s. Pesar, sentimiento. Llaki, llakiy, phuti",
    "afligido": "adj. Triste. Llakisqa, phutisqa.",
    "afligir": "v. tr. Causar pena. Llakichiy, phutichiy. Ch’irmachiy",
    "afligirse": "v. prnl. Sentir pena. Llakikuy, phutikuy, ch’irmakuy",
    "aflojar": "v. tr. Disminuir la presión o tirantez. Llawqhiy, llawqhichay, wayay, wayachay.",
    "aflorado": "p.p. Phanchasca.",
    "aflorar": "v. intr. Reventar como una flor. Phanchay",
    "afonía": "s. Defecto o ausencia total de voz por irritación o lesión de las cuerdas vocales y órganos ajenos. "
              "Ch’akaya, ch’aka kay",
    "afónico": "adj. Falta de voz. Ch’aka",
    "aforar": ". v. tr. Determinar la cantidad y valor de las mercaderías. Chaniylliy.",
    "afortunado": "adj. Illayuq, usapu, samiyuq, qillpuyuq.",
    "afrecho": "s. Salvado. Chhapa.",
    "afrenta": ". s. Vergüenza y deshonor. P’inqay, p’inqaycha, uyancha.",
    "afuera": "adv. Fuera del sitio en que uno está. Jawa. || adj. Descolocado, fuera de sitio. || Qilla.",
    "agachado": "adj. K’umu, k’umpu.",
    "agachar": ". v. tr. e intr. K’umuchiy.",
    "agacharse": "v. prnl. Uskhullukuy. K’umuy",
    "agarrar": ". v. tr. Asir fuertemente, coger. Jap’iy",
    "agasajar": "v. tr. Favorecer a uno con regalos o con afecto. Ch’uqichay, aypuy",
    "agavillar": "v. tr. Formar o atar gavillas para cargar. Payaqay. || Agavillar la mies segada, la paja o la leña. "
                 "Chullikuy. || Formar gavillas erguidas. Kallchay, qallchay.",
    "agigantado": "adj. De estatura mucho mayor que lo regular. Jatunkaray. Chhikankaray.",
    "agigantar": "v. tr. Dar proporciones gigantescas. Jatunyachiy, chhikanyachiy",
    "ágil": "adj. Ligero, pronto. Wayra chaki, wayralla.",
    "agitar": ". v. tr. Mover con frecuencia y violentamente. Maywiy",
    "aglomerar": ". v. tr. Amontonar. Qulluy, qutuy",
    "agobiado": "adj. Inclinado. P’akchi.",
    "agobiar": "v. tr. y prnl. Doblar la parte superior de un cuerpo. P’akchiy, k’umuchiy",
    "agolparse": "v. prnl. Juntarse de golpe. Qhuchuykukuy, qulluykukuy.",
    "agonizar": "v. intr. Estar en la gonía. Wañuy ñak’ariy, k’aywiy, wañuy p’itiy, p’iti kay.",
    "agosto": "s. Situwaki, chawawarki killa, chakraqunakuy killa",
    "agotable": "adj. Que se puede agotar. Tukukuq.",
    "agotado": "adj. Desmirriado, inservible. Yumpaqa",
    "agotar": "v. tr. Gastar del todo, consumir. Tukuy, sukllay.",
    "agraciado": "adj. K’achata.",
    "agradecer": "v. tr. Dar gracias. Pachiy, sullpay, allichay, yusparasunki.",
    "agradecimiento": ". s. Sentir gratitud. Pachi, sullpay ñiku",
    "agregar": "v. tr. Anexar, añadir. Yapay.",
    "agriar": "v. tr. Poner agrio. K’allkuchiy, k’arkuchiy, siqiyachiy, p’uchquchiy.",
    "agriarse": ". v. prnl. P’uchquy, satkhuyay.",
    "agrio": "adj. ácido, acerbo. K’allku, k’arku. Satkhu. P’uchqu",
    "agrupación": "s. Conjunto de personas agrupadas. Qutu, juñi, tanta, qhuchu, juñu. Waki",
    "agrupar": "v. tr. Reunir en grupo. Qutuy, jujuy, qhuchuy, tamachay, juñiy, ch’unkuy",
    "agruparse": " v. prnl. Qutukuy, ch’unkukuy, juñukuy, qhuchukuy, tamachakuy.",
    "agua": "s. Yaku, unu.",
    "aguantar": "v. tr. sufrir, soportar. Muchuy, urqhiy.",
    "aguardar": "v. tr. Esperar. Suyay.",
    "agudo": "adj. Delgado, afilado. Ñawch’i, k’awchi, q’awchi, t’urpu",
    "agüero": "s. Presagio de cosa futura. Raki, tapya. Wamulliku, umilliku.",
    "aguijón": "s. Púa del abdomen de algunos insectos y arácnidos. Wach’i.",
    "aguijonear": ". v. tr. Aguijar. T’uqsiy, t’uksuy.",
    "águila": ". s. Ave rapaz. Anka. Paka",
    "aguilucho": "s. Cría del águila. Anka irpa",
    "aguja": ". s. Yardilla, yawrilla, yarwicha.",
    "agujerear": "v. tr. Agujerar. Jutk’uy.",
    "agujero": "s. Abertura en alguna cosa. Jutk’u",
    "aguzar": ". v. tr. Hacer o sacar punta. K’awchiy",
    "ahí": "adv. En ese lugar. Chaypi. || A ese lugar. Chayman.",
    "ahondar": "v. tr. Cavar profundizando. Ukhuchay, p’ukruchay.",
    "ahora": "adv. Kunan",
    "ahorcar": ". v. tr. Colgar, sipiy, warkhuy, siq’uy",
    "ahorrar": "v. tr. y prnl. Economizar. Musiy, waqaychay.",
    "ahumar": ". v. tr. Poner una cosa al humo. Q’usñichiy, q’usñichay.",
    "ahuyentar": "v. tr. Hacer huir. Wayay, wikch’uy, ayqichiy. Qallquy (Perú).",
    "aimara": "adj. y s. Nombre de cultura y lengua aimara. Aymara: Nación aimara. Aymara llanta.",
    "airado": "adj. Colérico, agitado. Phiña, ch’usku",
    "aire": ". s. Wayracha, wayralli.",
    "aislar": "v. tr. Incomunicar, separar. Sapanchay",
    "aislarse": "v. prnl. Sapanchakuy",
    "ajar": "v. tr. Maltratar, arrugar. Naq’iy waqlliy, qhaqruy, q’allpiray.",
    "ají": "s. Pimiento picante. Uchu.",
    "ajo": "s. Ajus.",
    "ajorca": "s. Brazalete, pulsera. Chipana.",
    "ajustar": "v. tr. Arreglar. Tratándose de cuentas, reconocer y liquidar su importe. T’ituchay, t’iwchay",
    "ala": ". s. Miembro para volar. Riera, pharpa, rapra",
    "alabar": "v. tr. Elogiar. Añaychay, añayniy, jatunyachiy.",
    "alacena": "s. Armario hecho en la pared. Khatana, pirqa khatana, churana.",
    "alacrán": "s. Arácnido con una cola terminada en un aguijón venenoso. Sira sira.",
    "alado": "adj. Que tiene alas. Rikrayuq, raprayuq, pharpayuq",
    "alardear": "v. intr. Hacer alarde. Añaykachay, k’askiykachay, runaykachay.",
    "alargado": "adj. Largo, que tiene cierta longitud. Sayt’u.",
    "alargar": "v. tr. Estirar, hacer más largo. Suniyachiy, unachiy, aysay, sayt’uchay",
    "alargarse": "v. prnl. Suniyay, sayt’uyay",
    "alarmar": "v. tr. Asustar. Takurichiy.",
    "alba": "s. Primera luz del día. Paqar.",
    "albañil": "s. Alarife, constructor. Pirqaq, pirqay kamayuq",
    "albear": "v. intr. Blanquear, tirar a blanco. Yuraqyariy",
    "albergar": "v. tr. Hospedar. Qurpachay.",
    "albergue": "s. Alojamiento. Qurpa wasi",
    "albo": "adj. Blanco. Quyllu. fig. Rit’i.",
    "albor": "s. Luz del alba. Chhapu chhapu",
    "alborada": "s. Aurora, amanecer. Paqar, paqariy pacha, illariy, qaqñin pacha.",
    "alborear": "v. intr. Amanecer o rayar el día. Paqariy, illariy, yuraqyay. Sawlliy, p’unchay chayamuy.",
    "alborotador": "adj. Conmovedor. T’uki, ch’aqwalli, takurichiq, ch’aqwaq, ruqyaq.",
    "alborotar": "v. tr. Causar alboroto, inquietar, conmover. Ruqyay, takurichiy.",
    "alboroto": "s. Bullicio, vocerío o estrépito causado por una o varias personas. Ruqya, ch’aqwa",
    "alborozar": "v. tr. Causar gran placer o alegría. Chamachiy, kusichiy. || v. prnl. Alborozarse. "
                 "Camay, chamakuy, kusikuy",
    "alborozo": "s. Muestra de gran regocijo. Chama, kusi.",
    "alcahuete": "s. Persona que actúa como encubridora de relaciones amorosas o sexuales irregulares. Kacha puri.",
    "alcalde": "s. Jefe de un municipio. Llaqta kamayuq",
    "alcaldía": "s. Oficio o cargo de alcalde, o la oficina donde ejerce sus funciones. Llaqta kamay.",
    "alcanzar": "v. tr. Conseguir lo que se desea. Taripay, k’askay. || Tomar un objeto extendiendo la mano. "
                "Aypay, jaypay. || Entregar, poner en manos de uno. Jayway",
    "alcoba": "Aposento para dormir. P’itita",
    "alcurnia": "s. Ascendencia, linaje. Ayllu",
    "aldea": "s. Pueblo pequeño. Jallka, llaqtacha.",
    "aleccionar": "v. tr. Umallichiy. Juqhariy.",
    "alegrar": "v. tr. Causar alegría. Kusichiy, qapachay. || v. prnl. Alegrarse. Kusikuy, qapakuy.",
    "alegre": "adj. Lleno de alegría. Kusisqa, chamasqa.",
    "alegremente": "adv. Kusilla, kusi kusilla.",
    "alegría": "s. Júbilo, contento. Kusi, qapa, chama",
    "alejamiento": ". s. Acto y efecto de alejar o alejarse. Karuncha",
    "alejar": "v. tr. Poner lejos o más lejos. Karunchay, karuyachiy.",
    "alentar": "v. tr. Animar. Sunquchay. || v. intr. Respirar, cobrar aliento. Samay, samariy.",
    "alero": "s. Alar, parte saliente del tejado. Waqsu, waqtira.",
    "aleta": "s. Membrana a manera de ala. Rikracha, pharpacha.",
    "aletear": "v. intr. Mover mucho las alas o aletas. Pharaqiy, pharpay, p’atpay",
    "alfarero": "s. Fabricante de vasijas de barro. Manka llut’aq, sañu kamayuq.",
    "alfiler": "s. Clavillo para sujetar. T’ipki.",
    "alfombra": "s. Tapiz para cubrir el piso. Chusi, mant’a, mast’a.",
    "alfombrar": "v. tr. Cubrir con alfombra. Mast’ay, chusichay.",
    "algarabía": "s. Griterío confuso de varias personas que hablan a un tiempo. Ruqya, ch’aqwa.",
    "algarrobo": " s. Planta leguminosa. Thaqu",
    "algo": "pron. indent. Ima || adv. Un poco. As. Tumpa.",
    "algodón": "s. Planta textil. Utkhu, ampi. Unku",
    "alguien": "pron. indet. Pichari.",
    "algunos": "pron. Wakin, wakillan",
    "alhaja": "s. Joya, presea. Piñi, chuqi, illa umiña",
    "aliento": "s. Respiración. Samay, sama",
    "alimentar": "v. tr. Dar alimento. Mikhuchiy, panquchiy. || prnl. Alimentarse. Panquy, mikhuy.",
    "alimento": "s. Lo que nutre o da energía. Mikhuna, panqu.",
    "aliñar": "v. tr. Adornar. K’achachay. || Aderezar, preparar, componer. Allichay",
    "alisar": "v. tr. Poner lisa alguna cosa. Lluskuy, llusquchay, llunk’iy.",
    "alistar": "v. tr. Preparar. Wakichiy",
    "aliviador": "adj. Que alivia. Chhallachaq, jasachaq.",
    "alivianar": "v. tr. Aliviar, disminuir la carga, el peso o dolor. Chhallachay, chhallayachiy. || "
                 "prnl. Alivianarse. Llamsayay.",
    "aliviar": "v. tr. Ver ALIVIANAR.",
    "allá": "adv. En aquel lugar. Japaypi. || Hacia aquel lugar. Jaqayman",
    "allanar": "v. tr. Poner llano. Pampachay. || Allanar para cultivar o construir. Rukriy.",
    "allegar": "v. tr. Recoger. Tantay, pallay, jujuy",
    "allí": "adv. En aquel lugar. Jaqaypi. || A aquel lugar. Jaqayman.",
    "alma": "s. Espíritu , viveza. Nuna.",
    "almacen": "de papa bajo tierra. s. Qayru.",
    "almanaque": "s. Registro de los días dl año. Wata yupana.",
    "almirez": ". s. Mortero para machacar. Muchuqa, mut’a",
    "almohada": "s. Cojín para apoyar la cabeza. Sawna.",
    "almohadilla": "s. Almohada pequeña. Sawnacha. Juchuy sawna.",
    "almuerzo": "s. Comida que se toma por la mañana, antes de la principal. Paqarin mikhuy, paqarin llaqway. || "
                "Almuerzo que se toma la medio día o a primeras horas de la tarde. Chupi",
    "alocado": "adj. T’uki, witayasqa, thampisqa",
    "alojamiento": "s. Hospedaje, posada. Qurpa wasi.",
    "alojar": "v. tr. Hospedar, aposentar. Qurpachay.",
    "alpaca": "s. Mamífero rumiante de la familia de los camélidos. Allpaqa, paqu",
    "alquilar": "v. tr. Arrendar. neol. Arinsay",
    "alquiler": ". s. Precio en que se alquila alguna cosa. Harinsa, harinsa chani.",
    "altanero": "adj. Altivo, khaski khaski, saya saya, waphar",
    "altar": "s. Ara, especie de tribuna para actos importantes o celebraciones. Usnu",
    "alterar": "v. tr. Modificar, cambiar la esencia de una cosa. Wakjinayay. || prnl. Alterarse. Wakjinayay. || "
               "Conmoverse. Phiñarikuy, takurikuy",
    "altercar": "v. intr. Disputar. Ch’aqway, ayñanakuy, siminakuy, chhuqunakuy.",
    "altiplano": "s. Meseta de gran extensión y altitud. Puna, puna pampa.",
    "alto": "adj. Elevado, superior, arriba. Janaq, jana. ||. Sitio elevado. Pata. || De gran estatura. Jatunkaray.",
    "alumbrar": "v. intr. Parir la mujer. Wachay. || tr. e intr. Llenar de claridad o de luz. K’anchay.",
    "alumno": "s. Discípulo. Yachaqaq.",
    "alzar": "v. tr. Levantar. Juqhariy",
    "amado": "adj. Munasqa.",
    "amamantar": "v. tr. Dar de mamar. Ñuñuchiy.",
    "amanecer": "s. Tiempo durante el cual amanece. Paqar, paqarin, sut’iyay. || "
                "v. intr. Empezar a aparecer la luz del día. Paqariy, sut’iyay, yuraqyamuy",
    "amanecida": "s. Paqarin, paqar. Sut’iyay",
    "amansar": "v. tr. Domesticar. Kallkuchiy, llamp’uyachiy.",
    "amansarse": "v. prnl. Volverse manso. Llamp’uyay.",
    "amante": "adj. y s. Enamorado, persona apasionada por otra. Munaqi, munaq",
    "amar": "v. tr. Tener amor a personas o cosas. Munay, munakuy, waylluy. || Compadecer. Khuyay",
    "amargar": "v. intr. y v. tr. Tener sabor amargo. Jayaqiy, jayay. || v. tr. Picar, comunicar sabor desagradable "
               "a una cosa. Jayaqyachiy. || Causar aflicción. Phutichiy.",
    "amargo": "adj. Que amarga. Chaqaq, jaya, jayaq, qhatqi.",
    "amarillear": "v. intr. Amarillecer. Q’illuyay",
    "amarillento": "adj. Q’illuyasqa.",
    "amarillo": "adj. Q’illu",
    "amarradero": "s. Sitio donde se amarra a un animal o cosa. Watana.",
    "amarrar": "v. tr. Atar con amarras. Watay",
    "ambición": "s. Munapayay.",
    "ambicionar": "v. tr. Desear ardientemente alguna cosa. Munapayay.",
    "ámbito": "s. Contorno de un espacio. Kiti.",
    "ambos": "adj. pl. Los dos. Puraq, iskaynin",
    "amedrentar": "v. tr. Atemorizar. Manchachiy, llaklachiy, kharkachiy. || prnl. Amedrentarse. Manchachikuy.",
    "amenaza": "s. acción de amenazar. Mapas, kamayku.",
    "amiga": "de la mujer. s. Yanasa: Entre amigas. Yanasapura.",
    "amigarse": "prnl. Atillchakuy",
    "amígdala": "s. Glándula a la entrada del esófago. Amuqlli.",
    "amigo": "s. Atillcha, masi, sukna.",
    "amistarse": "prnl. Atillchakuy",
    "amojonar": "v. tr. Señalar con mojones los límites de una propiedad. Sayway, saywachay.",
    "amolar": "v. tr. Afilar. T’upay, k’awchiy, ñawchiy, t’upray, thupay",
    "amonestar": ". v. tr. Reprender. K’aymiy, khunay. || Advertir. Atikllay.",
    "amontonar": "v. tr. Poner en montón. Qulluy, qutuy, phinay, rawkhay. || Amontonar objetos largos. Taqway",
    "amor": "s. Inclinación o afecto a la persona. Munay. || Afecto entre personas. Munakuy. || Amor con ternura. "
            "Waylluy. || Compasión. Khuyay.",
    "amoratar": "v. tr. Poner o volver morado. Kullichay, kulliyachiy, saniyachiy. || "
                "prnl. Amoratarse. Kulliyay, saniyay.",
    "amplio": "adj. Extenso, dilatado. Kimra. || Ancho. Miqa.",
    "ampolla": "s. Vejiga formada por la elevación de la epidermis. Phusullu",
    "amputación": "s. Wit’u",
    "amputar": "v. tr. Cortar y separar enteramente del cuerpo un miembro o porción de él. Wit’uy, mut’uy",
    "amuleto": "s. Objeto que se le atribuye virtud sobrenatural. Illa, wak’a.",
    "amurallar": "v. tr. Murar. Pirqachay",
    "análisis": "s. Exámen minucioso. Khuski, qhawakipa",
    "analizar": "v. tr. Hacer análisis de algo. Khuskiy",
    "ananá": " Ananás o piña. s. Anana, achupalla",
    "anaranjado": "adj. De color de la naranja. Willapi.",
    "ancho": "adj. Sakha: De posaderas anchas. Sakha siki. || Amplio. Miqa",
    "anchura": "s. Kinray, kimray (sinón.: Latitud)",
    "anciana": "s. f. De mucha edad, vieja. Paya.",
    "ancianidad": "s. Decrepitud. Rukhu kay. || m. Machu kay. || f. Paya kay",
    "anciano": "s. m. Viejo. Machu. || adj. Decrépito. Rukhu.",
    "andar": "v. intr. Caminar, ir de un lugar a otro. Puriy. || Andar a pasos. Thatkiy",
    "andarín": ". adj. y s. Andariego. Wayra chaki.",
    "andas": "s. Camilla. Wantu.",
    "andén": "s. Corredor o sitio destinado para andar. Purina, malima.",
    "andino": "adj. y s. Relativo a la región de los Andes. Antiqpa, antipi kaq, antimanta kaq.",
    "andrajo": "s. Pedazo de ropa muy usada. Sapsa, llachapa, thanta.",
    "anegar": "v. tr. Inundar. Llukmay. || sumergir. Lluqllachiy, sinqachiy. || Anegarse. Sinqakuy",
    "anemia": "s. Pobreza de la sangre. Qasawi.",
    "ánfora": "s. Cántaro. P’uytu",
    "angosto": "adj. estrecho o reducido. K’ullku, k’ikllu. || Ceñido. K’ichki.",
    "ángulo": "s. Avertura de dos líneas que se cortan. K’uchu, chhuka, k’inki.",
    "angustia": "s. Aflicción. Wat’isamka, phuti, ñak’ari.",
    "angustiado": "adj. Afligido. Phutisqa, ullphu, wat’isamkasqa",
    "angustiarse": "v. prnl. Phutikuy, ñak’ariy, ullphukuy",
    "anidar": "v. intr. Hacer nido las aves o vivir en él. Q’isachay, q’isachakuy, thapachay, thapachakuy",
    "anillo": "s. Aro pequeño. Siwi.",
    "animal": " Doméstico. s. Uywa. // Arisco. s. K’ita.",
    "animar": ". v. tr. Estimular, alentar. Akyay, sunquchay, akyachiy",
    "ano": "s. Uquti.",
    "anoche": "adv. La noche de ayer. Ch’isi.",
    "anochecer": "v. intr. Llegar la noche. Ch’isiyay, tutayay. || s. Crepúsculo vespertino. Rankhi",
    "anónimo": ". adj. y s. Sin nombre o firma. Sutinnaq, mana sutiyuq",
    "antaño": "adv. Año que precedió al corriente. Qayna wata. || "
              "El tiempo antiguo. Ñawpa pachapi, wayna pachapi, unay.",
    "anteanoche": ". adv. La noche de anteayer. Qaninpa chisi.",
    "anteayer": ". adv. Qaninpa, qayninpa, qaynin p’unchaw.",
    "antebrazo": "s. Parte inferior del brazo, del codo hasta la muñeca. Apawa",
    "antelación": "s. Anticipación. Williwa",
    "antelar": ". v. tr. Anticipar. Williway.",
    "antepasado": "s. Abuelo, ascendiente. Apuski.",
    "antes": "adv. Denota prioridad. Nawpaq",
    "anticiparse": "v. prnl. Ñawpay, ñawpatay",
    "antiguamente": "adv. Ñawpa pacha.",
    "antigüedad": "s. Condición de antiguo o remoto. Ñawpa kay, wayma kay.",
    "antiguo": "adj. Que existe desde hace mucho tiempo. Ñawpa. || Usado, envejecido. Mawk’a. || "
               "Un objeto usado. Thanta",
    "antojadizo": "adj. Wanllapu, akllapu, (sinón.: Ávido)",
    "antojo": "s. Deseo vivo o pasajero. Muq’i, millp’u, añala",
    "anuario": "s. Libro de los sucesos de un año. Wataqillqa",
    "anublarse": "v. prnl. Phuyuy, phuyuykuy.",
    "anudar": ". v. tr. Hacer nudos. Khipuy, khipuchay.",
    "anular": "adj. Dedo, propio del anillo. Siwi ruk’ana. // v. tr. Invalidar. Q’ullwachay, q’ullway.",
    "anverso": "s. Cara principal de un objeto. Uyan",
    "anzuelo": "s. Útil de pesca. Jach’una, simp’i, pinta, challwana",
    "añadido": "adj. Yapasqa",
    "añadidura": "s. Aumento. Yapa.",
    "añadir": "v. tr. Aumentar. Yapay",
    "año": "s. Wata",
    "aovar": "v. intr. Poner huevos las aves. Runtuy",
    "apabullar": "v. tr. Aplastar deshacer con los pies. Thullkiy.",
    "apacentar": "v. tr. Hacer pacer al ganado. Michiy",
    "apachurrar": "v. tr. Convetir en pasta. Ñut’uy.",
    "apacible": "adj. Manso, pacífico. Llamp’u.",
    "apaciguar": "v. tr. Calmar, poner en paz. Ñañichiy, llamp’uchiy, thañichiy",
    "apadrinar": "v. tr. Acompañar como padrino a una persona. Watmuy.",
    "apagar": "v. tr. Extinguir. Thasnuy: Apaga el fuego. Ninata thasnuy. Nina wanuchiy",
    "apalear": "v. tr. Pegar con un palo. Q’asnuy, p’anay",
    "aparear": "v. tr. Ajustar una cosa con otra, de forma que queden iguales. Igualar. Khuskachay. || "
               "Separar por parejas. Yananchay. || Hacer o formar pareja. Pituchay. || "
               "Unir una cosa con otra formando par. T’inkiy, k’intiy",
    "aparecer": "v. intr. Manifestarse, mostrarse a la vista. Rikhuriy",
    "aparecido": "adj. Que se ha puesto a la vista. Rikhuriq, rikhurikuq.",
    "apariencia": "s. Aspecto exterior de una persona o cosa. Rikch’ay",
    "apartar": "v. tr. Separar. T’aqay, sapanchay, t’inkinnay.",
    "apartarse": "v. prnl. Alejarse, retirarse. Ithiy, ithiriy, anchhuy.",
    "apático": "adj. Sin vigor, que tiene apatía. Q’ayma sunqu",
    "apedrear": "v. tr. Lapidar, tirar piedras a una persona o cosa. Ch’amqay, chuqay. || "
                "Machucar a pedradas. Ch’aqiy.",
    "apegarse": "v. prnl. K’askakuy. || Apegarse excesivamente al trato de una persona. Mak’allikuy",
    "apellido": "s. Nombre de familia. Ayllu suti.",
    "apelotonar": "v. tr. Formar pelotón o pelotones. Muruq’uchay.",
    "apenarse": "v. prnl. Tener pena. Llakikuy. Phutikuy",
    "apenas": "adv. Penosamente. Ñak’ay, ñak’aymanta, yaqha mana, yaqhamanta",
    "apestoso": "adj. Que despide mal olor. Phutun, asnaq.",
    "apetito": "s. Apetencia, ganas de comer. Yariqha",
    "apilar": "v. tr. Formar pilas, amontonar. Qutuy. || Amontonar objetos alargados. Tawqay",
    "apiñar": "v. tr. Comprimir, agrupar apretadamente. Ñit’iy, k’ichkiy.",
    "apiñarse": "v. prnl. Ñit’inakuy, k’ichkinakuy, qullukuy.",
    "apisonar": "v. tr. Apretar el piso o pavimento. P’arpay, t’aqtay.",
    "aplanar": "v. tr. Hacer plano. P’arpay, t’aqtay, pampachay.",
    "aplastado": ". adj. Ñat’usqa, p’altachasqa.",
    "aplastar": "v. tr. Deformar una cosa aplastándola. Ñat’uy, p’altay",
    "aplazar": "v. tr. Suspender, retardar. Qhipanchay",
    "apocar": "v. tr. Reducir a menos. Pisichay, pisiyachiy.",
    "apocarse": "v. prnl. Encogerse, achicarse. K’uytukuy. || Volverse pusilánime. Samp’akuy",
    "apolillar": "v. tr. y v. prnl. Roer la polilla. Thutay",
    "aporcar": "v. tr. Acollar. Jallmay.",
    "aporrear": "v. tr. Golpear con garrote o palo. P’anay, q’asnuy.",
    "apostar": "v. tr. Hacer una apuesta. Misay",
    "apoyar": ". v. tr. Hacer que una cosa descance sobre otra. Q’imiy. || fig. Favorecer. Yanapay",
    "apreciar": "v. tr. Poner precio, estimar. Chaninchay",
    "aprecio": "s. Valuación, estima. Chani, chanin",
    "apremiar": "v. tr. Dar prisa. Utqhachiy, chaychay, jump’ichiy",
    "aprender": "v. tr. Adquirir el conocimiento de una cosa. Yachaqay.",
    "apresar": "v. tr. Aprisionar, encarcelar. Piñaschay, watinkay.",
    "apresurar": "v. tr. Dar prisa, acelerar. Utqhay, utqhachiy",
    "apretar": "v. tr. Comprimir, tupir. Mat’iy. || v. prnl. Apretarse, compactarse, espesarse. Pipuyay.",
    "aprisco": "s. Lugar donde se recoge el ganado. Jip’i, jip’ina.",
    "aprisionar": ". v. tr. Poner en prisión. Paqumay, piñaschay.",
    "aproximación": "s. Acercamiento. Asuy, qayllaku",
    "apuesto": "adj. Gallardo, gentil. Wallpari, k’achata",
    "apuñalar": ". v. tr. Dar de puñaladas. T’uqsiy",
    "apuntalar": "v. tr. Poner puntal o puntales. Chakay, q’imiy.",
    "aquel": "pron. dem. Jaqay.",
    "aquella": "pron. dem. Jaqay.",
    "aquello": "pron. dem. Jaqay.",
    "aquí": "adv. En este lugar. Kaypi. || A este lugar. Kayman.",
    "aquietar": "v. tr. Tranquilizar, sosegar. Qasichiy",
    "arado": "s. Instrumento de trabajo agrícola. Taklla. || Chaki taklla. Arado de pie",
    "araña": "s. Arácnido que segrega un hilo sedoso. Kusi kusi.",
    "arañar": "v. tr. Herir con las uñas. Jasp’iy, rach’iy, silluy",
    "arañazo": "s. Herida superficial, rasguño. Jasp’i, rach’i, rachi.",
    "arar": "v. tr. Remover la tierra con el arado. Yapuy, llamk’ay. || Barbechar. Qhulliy.",
    "árbol": "s. Planta perenne de tronco leñoso y elevado. Sach’a. || Árbol frutal. Mallki.",
    "arboleda": "s. Sitio con árboles. Sach’a sach’a",
    "arcilla": "s. Sustancia mineral plástica. Llank’i, llink’i, k’inku. T’uru.",
    "arco iris": "s. K’uychi.",
    "arder": ". v. intr. Quemarse, consumirse con el fuego. Rawray. || Producirse la comezón. K’aray.",
    "arena": "s. Conjunto de partículas de roca. T’iwu, aqu",
    "arete": "s. Zarcillo, pendiente. Ninriquri.",
    "argolla": "s. Anillo de boda. SIPI.",
    "arisco": "adj. Huraño, cerril, insociable. T’illa.",
    "armadijo": ". s. Trampa para cazar animales. Tuqlla, tuqllana, chipa, urmana",
    "armadillo": "s. Quirquincho. Khirkinchu, khirki.",
    "aro": "s. Rueda. Tinkullpa.",
    "aroma": "s. Perfume, fragancia. Kuntu, q’apaq.",
    "aromatizar": "v. tr. Dar aroma a alguna cosa. Kuntuy, q’apachiy",
    "arraigar": "v. intr. y prnl. Echar raíces. Saphiy, saphichay, saphichakuy",
    "arrancar": "v. tr. Sacar o quitar con violencia una cosa del lugar a que está adherida, o de que forma parte. "
                "Saq’ay, t’iray, sik’iy",
    "arrasar": "v. tr. Allanar. Pampachay. || Talar. Chaquy.",
    "arrastrar": "v. tr. Llevar por el suelo. Qharastay, qhatatay, qhatatiy.",
    "arrastrarse": "v. prnl. Suchuy.",
    "arrear": "v. tr. Estimular o conducir al ganado. Qhatiy",
    "arremangar": ". v. tr. Recoger hacia arriba las mangas o la ropa. Q’impiy, q’allpay, llint’ay",
    "arrendar": "v. tr. neol. Dar o tomar por arriendo. Arinsay",
    "arriba": "adv. En lo alto, en la parte alta. Wichay",
    "arrimar": "v. tr. Apoyar. Q’imiy. || v. prnl. Apoyarse. Q’imikuy",
    "arrinconar": "v. tr. Poner en un rincón. K’uchunchay.",
    "arrodillar": " v. tr. Hacer que uno hinque las rodillas. Qunqurichiy. || "
                  "v. prnl. Ponerse de rodillas. Qunquriy, qunqurikuy",
    "arrodillarse": "v. prnl. Qunquriy",
    "arrojar": ". v. tr. Lanzar con fuerza una cosa. Ch’amqay. (sinón.: Tirar). || "
               "Echar fuera. Wikch’uy (sinón.: Botar). || "
               "Estrellar, impeler, empujar violentamente con torpeza. Chuqay.",
    "arrollar": "v. tr. Envolver, enrollar. Ch’uwiy",
    "arruga": "s. Pliegue en la piel. Sip’u. || Pliegue irregular de una cosa. K’usu.",
    "arrugado": "adj. Hecho pliegues, fruncido. Sip’usqa, k’usu, q’isti",
    "arrugar": ". v. tr. Hacer arrugar. K’usuchay, k’usuy, sip’uy",
    "arrullar": "v. tr. A un niño. Chhukuy.",
    "articulación": "s. Unión de un hueso con otro. Muqu",
    "asado": "s. Carne asada. Kanka",
    "asador": "s. Utensilio para azar. Kankana.",
    "asaltar": "v. tr. Acometer alevosamente. Kapujay, phawaykuy",
    "asar": " v. tr. Someter un manjar al fuego. Kankan",
    "ascender": "v. intr. Subir. Wichariy",
    "ascendente": "adj. Wichariq, siqaq.",
    "asco": "s. Desagrado, repugnancia. Milla, millay",
    "asear": "v. tr. Hacer limpieza. Llump’achay. || Barrer con escoba. Pichay. || Adornar. Sumaqchay.",
    "asegurar": ". v. tr. Poner en sitio seguro, guardar, preservar. Jallich’ay, waqaychay",
    "asemejar": "v. tr. Representar una cosa como semejante a otra. Kikinchay, masichay.",
    "asentarse": "v. prnl. Tomar asiento o establecerse en un lugar. Tiyakuy",
    "asentir": "v. intr. Admitir como cierta o conveniente una cosa. Juñiy, jumñiy.",
    "asesinar": ". v. tr. Matar. Wañuchiy",
    "así": "adv. De esta o de esa manera, de tal suerte. Jina, ajina.",
    "asiento": "s. Silla, banco u otro objeto para sentarse. Tiyana, chukuna",
    "asir": "v. tr. Tomar con las manos. Jat’alliy, jap’iy",
    "asma": "s. Inflamación de los bronquios. Qharqa.",
    "asociación": "s. Waki",
    "asolear": "v. tr. Poner al sol. Tuntichiy. || Asolear la oca u otros productos. Qawichiy. || "
               "v. prnl. Asolearse. Tuniy, qawiy.",
    "áspero": "adj. Escabroso, no suave al tacto. Qhachqa, chanca.",
    "asquear": "v. tr. e intr. Sentir asco de alguna cosa. Millachikuy.",
    "asqueroso": "adj. Que causa asco. Millana, khuchi.",
    "astilla": "s. Fragmento producido por rotura. K’ullpi",
    "astillar": "v. tr. Hacer astillas. K’ullpiy",
    "astuto": "adj. Bellaco. Challi",
    "asustar": "v. tr. Dar o causar susto. Manchachiy",
    "asustarse": "v. prnl. Manchariy",
    "atado": "p.p. Amarrado. Watasqa. || 2. s. Bulto. Q’ipi",
    "atajar": "v. tr. Detener. Jark’ay",
    "atar": "v. tr. Watay",
    "atardecer": "v. intr. Caer la tarde. Sukhayay.",
    "atender": "v. tr. e intr. Escuchar. Uyapay.",
    "aterrar": "v. tr. Causar terror. Llaksachiy",
    "atizar": "v. tr. Alimentar el fuego, quemar. Inqhay",
    "atolondrado": "adj. Aturdido. Thanqu, thampi.",
    "atolondramiento": "s. Turbación. Thanqu. atorar. v. tr. Atragantar, atascar. Chakachiy. || "
                       "Asfixiar. K’akmay. || v. prnl. Atascarse. Chakachikuy",
    "atragantarse": "v. prnl. No poder tragar algo que se atraviesa en la garganta. Chakachikuy.",
    "atrás": "adv. Qhipa. || Wasa. Con respecto a los objetos.",
    "atribuir": "v. tr. Achacar. Tumpay.",
    "atribular": ". v. tr. Acongojar, afligir. Llakichiy, phutichiy",
    "atropellar": "v. tr. Pisotear. Tharmiy, t’ustiy",
    "aullar": "v. intr. Dar aullidos. Waqarqachay. Ayquy, awyay.",
    "aumentar": "v. tr. Añadir, adicionar. Yapay",
    "aumento": ". s. Añadidura. Yapa.",
    "aunar": "v. tr. Unificar, unir, juntar. Jukllachay",
    "aurora": " s. Alba. Paqar, qhiyantupa.",
    "ausentarse": "v. prnl. Alejarse uno. Anchhuriy",
    "autor": ". s. Quien ha hecho o creado algo. Ruwaq, ruwaqi. || Escritor. Qillqaq",
    "autoridad": "s. Potestad. Carácter o representación de una persona por su mérito o poder. Kamachiq",
    "auxiliar": "v. tr. Dar auxilio, ayudar. Yanapay",
    "avaro": "adj. y s. Que tiene avaricia. Mich’a, maklla.",
    "ave": "s. P’isqu.",
    "avenida": "s. Riada, crecida impetuosa. Lluqlla",
    "aventajar": "v. tr. y prnl. Adelantar, pasar, llevar ventaja. Yallitamuy",
    "aventar": "v. tr. Hacer aire a alguna cosa. Wayrachiy.",
    "avergonzar": "v. tr. Afrentar, causar vergüenza. P’inqachiy. || v. prnl. Tener vergüenza. P’inqakuy.",
    "avinagrado": "adj. Agrio, hecho vinagre. K’arku.",
    "avión": " s. Aeroplano. Maraq.",
    "avisar": ". v. tr. Anunciar. Willay, atikllay.",
    "aviso": "s. Noticia. Villana, atiklla.",
    "avispa": "s. Insecto de alas membranosas. Lachiwana.",
    "axila": "s. Sobaco. Lluk’i, wallak’u, wayllak’u, wallwak’u.",
    "ayer": "adv. Qayna.",
    "ayuda": "s. Acto y efecto de ayudar. Yanapa, jayma, jawma.",
    "ayudar": "v. tr. Yanapay. || "
              "Prestar ayuda, acudir en servicio de alguna persona en prestación desinteresada. Jaymay.",
    "ayunar": "v. intr. Dejar de comer. Sasiy, sasikuy.",
    "ayuno": "s. Sasi.",
    "azotar": "v. tr. Dar azotes. Jasut'iy, siq’uy, suq’ay.",
    "azufre": "s. Sallina",
    "azul": "adj. Azur, de color del cielo. Anqas",
    "azulear": "v. intr. Tirar a azul. Anqasyay",
    "baba": ". s. Saliva espesa y viscosa. Llawsa. Thawti.",
    "babear": "v. intr. Echar baba. Llawsay, thawtiy",
    "baboso": " adj. y s. Que echa babas. Llawsasuru, llujusapa.",
    "bailar": "v. intr. Mover el cuerpo al compás de la música. Tusuy.",
    "baile": "s. Danza. Tusu",
    "bailarín": "adj. y s. Persona que ejercita o profesa el arte de bailar. Tusuq",
    "bajada": "s. Acto de bajar. Uray",
    "bajar": "v. intr. Descender. Uraykuy, uraqay. || v. tr. Bajar una cosa de un lugar elevado. Uranchay, urachay",
    "bajo": "adj. Lo que está en un lugar inferior respecto a otras cosas de la misma clase. Ura, urin",
    "balanza": "s. Instrumento para pesar. Aysana.",
    "balbucear": "v. intr. Hablar o leer con pronunciación dificultosa y vacilante. Janlluy. || Tartamudear. Aklluy.",
    "balón": "s. Pelota. P’utu. Papawki. || Fardo grande. Jatun q’ipi.",
    "balsa": "s. Especie de barco hecho de juncos para navegar. Walsa. || Charca. Muchacha.",
    "bambolear": "v. intr. Oscilar, balancearse. Llawiykachay, chankaykachay",
    "banana": "s. Plátano. Puquchi. Latanu",
    "banco": "s. Asiento. Tiyana, chukuna",
    "bandada": " s. Conjunto de aves. Tanta, waphara tama.",
    "bandeja": "s. Recipiente en el cual se sirve comida, bebidas, etc. Lata, wantar",
    "bandera": "s. Emblema o insignia nacional. Wiphala. Unancha.",
    "bañado": "adj. Aseado. Armasqa.",
    "bañar": ". v. tr. Meter el cuerpo o parte de él en agua con el fin de asear. Armay.",
    "bañarse": "v. prnl. y r. Lavarse el cuerpo con agua. Armakuy.",
    "baño": ". s. Agua o líquido para bañar o bañarse. Armana",
    "barato": "adj. De poco precio. Chaninnaq, pisi chaniyuq. fig. Chhala.",
    "baratear": "v. tr. Dar una cosa por menos de su precio. fig. Chhalay",
    "barba": "s. Parte de la cara, debajo de la boca. K’aki. || "
             "Pelo que nace en esta parte de la cara y en las mejillas. Sunkha, chhunka",
    "barbudo": "adj. Que tiene muchas barbas. Sunk’asapa, ch’apu",
    "barco": "s. Embarcación para transportar mercancías o personas. Wamp’u.",
    "barranco": ". s. Barranca, despeñadero. Qhanqa.",
    "barrer": "v. tr. Asear, limpiar. Kaychuy. || Barrer con la escoba. Pichay.",
    "barriga": "s. Wiksa.",
    "barrigudo": "adj. Que tiene la barriga grande, panzón. T’ini, wiksasapa",
    "barro": ". s. Masa de tierra y agua. T’uru. || Barro de la cara. Muchi.",
    "base": ". s. Base de objetos. Base de jarro. Yuru sik’i.",
    "bastante": "adj. Que basta. Achkha, chay chica, manchay. || adv. Demasiado. Ancha",
    "bastón": "s. Vara para apoyarse al andar. Tawna",
    "basura": "s. Inmundicia, desperdicios. Q’upa.",
    "basural": "s. Lugar basurero, muladar. Q’upa pata.",
    "batalla": "s. Lucha, combate entre dos grupos bélicos. Awqanaku, ch’umpa, maqanaku.",
    "batallar": "v. intr. Pelear, combatir. Awqanakuy, ch’umpanakuy, maqanakuy",
    "batata": "s. Camote, tubérculo comestible. Apichu",
    "batir": "v. tr. Un líquido. Qaywiy.",
    "bautizar": "v. tr. Sutichiy.",
    "bazo": "s. Órgano impar parecido a una glándula, situado en la parte posterior izquierda del abdomen, "
            "entre el riñón izquierdo, el diafragma y las falsas costillas. Wiq’aw.",
    "bebé": ". s. Nene. Niño. Wawa.",
    "beber": "v. intr. y tr. Ingerir un líquido. Upyay, ukyay, upiy.",
    "bebida": "s. Líquido que se bebe. Upyana, ukyana.",
    "becerro": "s. Novillo. Uña",
    "begonia": "s. Planta perenne, originaria de América, de la familia begoniáceas. Achanqara",
    "bello": "adj. Hermoso, lindo. Sumaq, k’acha, añay.",
    "bendecir": "v. tr. Alabar. Añaychay, añay ñiy, yupaychay",
    "benjamín": "s. fig. Hijo menor, el más mimado de sus padres. Juqi, chanaku.",
    "beodo": "adj. Embriagado, borracho. Machasqa",
    "besar": ". v. tr. Tocar suavemente o acariciar a una persona o cosa con los labios. Much’ay.",
    "beso": "s. Acción y efecto de besar. Much’a",
    "biceps": "adj. y s. Músculos pares que tienen por arriba dos porciones o cabezas. Challwan, mach’in, mach’ika",
    "bicolor": "adj. De dos colores. Misa, misa llimphi.",
    "bicho": "s. Animal pequeño. Khuru",
    "bien": "adv. De buena manera, sin inconveniente o dificultad. Allin. || adj. y s. Allin, sumaq",
    "bigote": "s. Pelo sobre el labio superior. Takachu.",
    "bilis": ". s. Humor viscoso, de color amarillo verdoso, amargo, segregado por el hígado. Jayaqi.",
    "bisabuela": "s. f. Awkilla.",
    "bisabuelo": "s. m. Machu yaya",
    "bisnieta": "s. f. Respecto de una persona, hija de su nieto o de su nieta. Ampullu.",
    "bisnieto": "s. m. Respecto de una persona, hijo de su nieto o de su nieta. Tari.",
    "bizco": "adj. Rirq’u, lirq’u churchu.",
    "blanco": "adj. y s. De color de nieve o leche. Yuraq. || Blanco impecable o inmaculado. Quyllu",
    "blancura": ". s. Calidad de blanco. Yuraq kay. || "
                "Color como la nieve. Rit’i kay. || Color blanco impecable. Quyllu kay",
    "blando": "adj. Suave, que cede fácilmente al tacto. Llamp’u. || "
              "Esponjoso y suave. Phupa: Este pan está bien blando. Kay t’antaqa allin phupa. || "
              "Manso, de carácter apacible. Llamp’u. || Muelle. T’ikmu",
    "blandura": "s. Dulzura en el trato. Llamp’u kay. || Suavidad. T’ikmu kay.",
    "blanquear": "v. tr. Poner blanca una cosa. Yuraqyachiy",
    "bloquear": "v. tr. Poner o hacer bloqueo. Jark’apay.",
    "boa": ". s. Ofidio de gran tamaño. Ati mach’aqway, amaru",
    "bobo": "adj. y s. De corto entendimiento. T’ara, upalu, thamalu.",
    "boca": "s. Cavidad por donde se toma el alimento. Simi.",
    "bocina": "s. Trompeta de caracol. Qipa. || Bocina hecha de asta. Pututu",
    "bocio": "s. Tumoración de la glándula tiroides que produce abultamiento en la parte anterior del cuello. Q’utu.",
    "bocón": ". adj. y s. fam. Que habla mucho y echa bravatas. Simisapa. || fig. De boca grande. Jatun simiyuq.",
    "boda": "s. Casamiento. Sawa.",
    "bofetada": "s. Golpe que se da en el rostro con la mano abierta. T’aqlla, ch’aqlla. || "
                "Bofetada que produce un ruido. Laq’a. || Golpe con la parte opuesta de la palma de la mano. Jinch’a.",
    "boina": ". s. Gorra redonda y sin visera de una sola pieza. Qhumpu ch’ulu",
    "bola": "s. Cuerpo esférico. Murq’u.",
    "boleadoras": ". s. pl. Instrumento con que se arroja a los pies o al cuello de un animal para apresarlo. "
                  "Se compone de dos o tres piedras, forradas de cuero y sujetas a sendas guascas. Riwi",
    "bolsa": "s. Talega, squillo. Wayaqa. || Bolsa pequeña para llevar coca. Ch’uspa. || "
             "Bolsa o saco grande, costal. Kutama.",
    "bolso": "s. Bolsa pequeña para llevar dinero o ropa. Tamaña",
    "bombo": "s. Tambor grande que se toca con una maza y se emplea en orquestas y bandas. Wankar, mama wankara.",
    "bondad": "s. Calidad de bueno. K’acha kay, alli kay, alli sunqu kay, llamp’u kay, llamp’u sunqu kay.",
    "bondadoso": "adj. Lleno de bondad. Alli kaq, alli sunqu, k’acha sunqu, alli sunquyuq.",
    "bonete": ". s. Gorro usado por los eclesiásticos. Ch’ullu",
    "boquiabierto": "adj. Que tiene la boca abierta. Janlla simi, simi kicha, janllarayaq.",
    "borbollar": "v. intr. Borbollear, borbollonear. Phullpuy, phulluyuy, t’impuy, phulluqiy.",
    "borbotar": "v. intr. Ver BORBOLLAR.",
    "bordado": "s. Bordadura. Tukapu",
    "borracho": "adj. y s. Ebrio, embriagado por la bebida. Machasqa",
    "borroso": "adj. Que no se distingue con claridad. Ayphu, aypha",
    "bosque": "s. terreno poblado de árboles. Sach’asach’a",
    "bosta": "s. Estiércol de animales caballares. Uchha, chusu. || Estiércol barroso de los corrales. Khara. || Boñiga, estiércol de ganado vacuno. Q’awa",
    "bostezar": ". v. intr. Inspirarlenta y profundamente, abriendo mucho la boca. Janyay.",
    "bostezo": ". s. Inspiración lenta y profunda. Janya, janyay, janllariy",
    "botar": ". v. tr. Arrojar o hechar con violencia. Wikch’uy. || Arrojar con torpeza, lanzar con toda fuerza, tirar. Chuqay.",
    "botón": "s. Capullo. Mukmu.",
    "boxeo": "s. Lucha a puñetazos. Ñuk’a, ñuk’anaku.",
    "bozal": "s. Objeto que se pone en el hocico de algunos animales. Sinqarpu, yukuma.",
    "bragadura": "s. Entrepiernas del hombre o del animal. Phaka. K’illka.",
    "brasa": "s. Leña o carbón incandescente. Sansa.",
    "brasero": "s. Vasija de metal o barro para fuego usada por los curanderos y adivinos. Thiya.",
    "bravío": "adj. Freroz, indómito, salvaje. Sallqa.",
    "bravo": "adj. Valiente, esforzado. Wapu, sinchi, phiña. Mana llakllaq.",
    "brazada": "s. Braza,, media de longitud. Ch’utakaski.",
    "brazalete": "s. Pulsera. Chipana. || Cóllar. Wallqa",
    "brazo": "s. Miembro superior del cuerpo, desde el hombro hasta la mano. Riera",
    "brete": "s. Cepo de hierro que sirve para sujetar los pies a los reos. Chaki chipana.",
    "breve": "adj. De corta extensión o duración. Jayri",
    "brevemente": "adv. Prestamente, jayri",
    "brevedad": "s. Corta extensión o duración de una cosa, acción o suceso. Jayri kay.",
    "bribón": "adj. y s. Pícaro, bellaco. Challi. || Dado a la burla, payaso. P’aqpaku",
    "brillante": "adj. Que brilla. Lliphiq, k’anchaq.",
    "brillar": ". v. intr. Resplandecer. Lliphiy, lliphipiy. || Alumbrar. K’anchay",
    "brincar": "v. intr. Dar brincos o saltos. Phinkiy",
    "brinco": "s. Salto brusco con ambos pies. Phinki.",
    "brindar": "v. intr. Manifestar, al ir a beber vino u otro licor, el bien que se desea a personas o cosas. Anqusay.",
    "brindis": "s. Acto de brindar. Anqusa.",
    "brisa": "s. Viento suave. Wayrari.",
    "broche": "s. Ch’itana. || Aguja o alfiler que se prende en el vestido. T’ipana.",
    "bromear": "v. intr. Hacer bromas. Sawkay, sawkarikuy, pukllakuy, pukllarikuy",
    "bromista": "adj. y s. Aficionado a bromear. Sawkalli, sawka rimaq.",
    "bronce": "s. Aleación de cobre y estaño, de color amarillento, tenaz y sonora. Chaqru anta.",
    "brotar": "v. intr. Nacer o salir la planta de la tierra. P’utuy. || Nacer renuevos de las plantas. Ijiy. || Filtrar o exudar el agua u otro líquido. Ch’illchiy.",
    "bruja": ". s. Lechuza, ave rapaz. Ch’usiq, ch’usiqa",
    "brujería": "s. Actividads extraordinarias a las que se dedican los brujos y las brujas. Layqaykuna.",
    "brujo": "adj. Persona que tiene pacto con el diablo. Layqa. || Adivino, agorero. Watuq",
    "buche": "s. Bolsa membranosa de las aves para recibir la comida. Ch’iti",
    "bueno": "adj. Que tiene bondad en su género. Sumaq. || Bueno, sano. Alli. || Gustoso, agradable. K’acha",
    "bufanda": "s. Prenda para abrigar el cuello. Aqullka.",
    "bufón": "adj. y s. Persona que servilmente hace reír a otros. Qamchu, asichiq, sawka rimaq.",
    "búho": "s. Ave rapaz nocturna, estrígida, de ojos grandes. Juku, tuku.",
    "buitre": "s. Ave rapaz que se nutre de animales muetos. Suwiq’ara, suwintu",
    "bulto": "s. Volumen o tamaño de cualquier cosa. Q’ipi",
    "bulla": "s. Gritería, bullicio. Ch’aqwa",
    "bullicioso": "adj. Que mete o hace bulla. Ch’aqwilli.",
    "burbuja": "s. Ampolla de aire en el agua. Phukpu",
    "burbujear": "v. intr. Levantar burbujas. Phukpuy",
    "burdo": "adj. Tosco, grosero. Ramphu, runkhi",
    "burla": "s. Mofa, chanza. Sawka.",
    "burra": "s. f. Asna. China asnu.",
    "burro": "s. m. Asno. Urdu asno.",
    "buscado": "p.p. Mask’asqa.",
    "buscar": "v. tr. Inquirir, hacer diligencias para encontrar o conseguir algo. Mask’ay. || Escudriñar, rebuscar. K’utkiy.",
    "busto": " s. Parte superior del cuerpo humano. Qhasqu, wanki.",
    "buzo": "s. El que trabaja sumergido en el agua. Ch’ulltuq, ch’ulltuq runa.",
    # C
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

}
